accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/<int:user_id>/', views.profile_page, name='profile'),
    path('ban/', views.ban_user, name='ban'),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.index, name='index'),
    path('thread', views.create_thread, name='new_thread'),
    path('thread/<int:thread_id>', views.thread_view, name='thread_page'),
    path('thread/lock/', views.lock_thread, name='lock_thread'),
    path('board/<int:board_id>', views.board, name='board_page'),
    path('board/new/', views.create_board, name='new_board'),
    path('board/delete/', views.delete_board, name='delete_board'),
]

bulletin_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('accounts.urls')),
    path('', include('boards.urls')),
    path('api/', include('bulletin_board.api_router')),
    path('api-auth', include('rest_framework.urls')),
    path('users/', include('allauth.urls')),
]

templates/base.html
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Django Bulletin Board</title>
    <meta name="description" content="The HTML5 Herald">
    <meta name="author" content="SitePoint">


</head>

<body>
<h1><a href="/">Home</a></h1>
{% if request.user.userprofile.id %}
 <a href="{% url "users:profile" request.user.userprofile.id %}">My Profile</a><br>
 <a href="{% url "users:logout" %}">Logout</a>
{% endif %}

{% if not request.user.is_superuser %}
{% block content %}

{% endblock %}
{% else %}
    <h3>Please logout as superuser to use the thread.</h3>
{% endif %}
</body>
</html>