accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/<int:user_id>/', views.profile_page, name='profile'),
    path('ban/', views.ban_user, name='ban'),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.index, name='index'),
    path('thread', views.create_thread, name='new_thread'),
    path('thread/<int:thread_id>', views.thread_view, name='thread_page'),
    path('thread/lock/', views.lock_thread, name='lock_thread'),
    path('board/<int:board_id>', views.board, name='board_page'),
    path('board/new/', views.create_board, name='new_board'),
    path('board/delete/', views.delete_board, name='delete_board'),
]

bulletin_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('accounts.urls')),
    path('', include('boards.urls')),
    path('api/', include('bulletin_board.api_router')),
    path('api-auth', include('rest_framework.urls')),
    path('users/', include('allauth.urls')),
]

boards/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.aggregates import Max
from django_extensions.db.models import TimeStampedModel
from ordered_model.models import OrderedModel

from accounts.models import UserProfile
from django.core.exceptions import ValidationError


class Board(OrderedModel, TimeStampedModel):
    name = models.CharField(max_length=255)
    creator = models.ForeignKey(UserProfile, related_name='boards', on_delete=models.CASCADE, limit_choices_to={'role':2})

    def clean(self):
        try:
            if not self.creator.role == 2:
                raise ValidationError({'creator': 'Creator is not an admin.'})
        except:
            pass

    @property
    def position(self):
        return self.order

    def __str__(self):
        return self.name

    def __repr__(self):
        return self.name

    def total_posts(self):
        return Post.objects.filter(thread__board=self).count()

    @property
    def sort_threads(self):
        return self.threads.annotate(most_recent=Max('posts__created')).order_by('-most_recent')

    def thread_with_latest_post(self):
        try:
            return self.sort_threads[0]
        except IndexError:
            pass

    def clean(self):
        if not self.creator.role == 2:
            raise ValidationError('Board should be created by admin')

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)


class Thread(TimeStampedModel):
    board = models.ForeignKey(Board, related_name='threads', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    posted_by = models.ForeignKey(UserProfile, related_name='threads', on_delete=models.CASCADE)
    is_locked = models.BooleanField(default=False)

    @property
    def posted_on(self):
        return self.created

    def __str__(self):
        return self.title

    def __repr__(self):
        return self.title

    def get_latest_post(self):
        try:
            return self.posts.order_by('-created')[0]
        except IndexError:
            pass


class Post(TimeStampedModel):
    thread = models.ForeignKey(Thread, related_name='posts', on_delete=models.CASCADE)
    message = models.TextField()
    posted_by = models.ForeignKey(UserProfile, related_name='posts', on_delete=models.CASCADE)

    @property
    def posted_on(self):
        return self.created

boards/forms.py
from django import forms

from .models import Board, Thread, Post


class AdminBoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['name', 'creator']

    position = forms.IntegerField(max_value=Board.objects.count() - 1, min_value=0)

    def save(self, commit=True):
        board = super().save(commit=False)
        board.to(self.cleaned_data['position'])
        board.save()
        return board


class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['name']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['message']


class ThreadForm(forms.ModelForm):
    class Meta:
        model = Thread
        fields = ['title', 'board']

    message = forms.CharField(widget=forms.Textarea, required=True)

boards/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, reverse, get_object_or_404

from boards.forms import ThreadForm, PostForm, BoardForm
from boards.models import Board, Thread, Post


# Create your views here.
@login_required()
def index(request):
    boards = Board.objects.order_by('order')

    return render(request, "board/index.html", {'boards': boards})


@login_required()
def create_thread(request):
    if request.method == 'POST':
        form = ThreadForm(data=request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            posted_by = request.user.userprofile
            message = form.cleaned_data['message']
            board = form.cleaned_data['board']
            thread = Thread.objects.create(board=board, title=title, posted_by=posted_by)
            Post.objects.create(posted_by=posted_by, thread=thread, message=message)

        return redirect(reverse('boards:index'))

    form = ThreadForm()
    return render(request, "board/new_thread.html", {'form': form})


@login_required()
def thread_view(request, thread_id):
    thread = get_object_or_404(Thread, pk=thread_id)
    if request.method == 'POST':
        form = PostForm(data=request.POST)
        if form.is_valid():
            Post.objects.create(thread=thread, message=form.cleaned_data['message'], posted_by=request.user.userprofile)

    form = PostForm()
    return render(request, "board/thread_page.html",
                  {'posts': thread.posts.order_by('-created'), 'form': form, 'thread': thread})


@login_required()
def lock_thread(request):
    thread = get_object_or_404(Thread, pk=request.POST.get('thread_id'))
    if request.method == 'POST' and not request.user.userprofile.role == 0:
        if thread.is_locked:
            thread.is_locked = False
        else:
            thread.is_locked = True
        thread.save()
    return redirect(reverse('boards:board_page', args=(thread.board_id,)))


@login_required()
def board(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    # Note: Solve one-to-many lookups Thread.objects.order_by('posts__created')
    threads = board.sort_threads
    return render(request, "board/board.html",
                  {'board': board, 'threads': threads})


@login_required()
def create_board(request):
    if not request.user.userprofile.role == 2:
        return redirect('/')

    if request.method == 'POST':
        form = BoardForm(data=request.POST)
        if form.is_valid():
            Board.objects.create(name=form.cleaned_data['name'], creator=request.user.userprofile)
            return redirect('/')
        else:
            return render(request, 'board/new_board.html', {'form': form})
    else:
        form = BoardForm()
        return render(request, 'board/new_board.html', {'form': form})


@login_required()
def delete_board(request):
    if not request.user.userprofile.role == 2:
        return redirect('/')

    if request.method == 'POST':
        board_id = request.POST.get('board_id')
        Board.objects.get(id=board_id).delete()

    return redirect(reverse('boards:index'))

templates/board/board.html
{% extends "base.html" %}
{% block content %}

    <h1>{{ board.name }}</h1>
    Number of threads: {{ board.threads.count }}

    {% if threads %}
        {% for thread in threads %}
            <div class="thread">
                <a href="{% url "boards:thread_page" thread.id %}"><h4>{{ thread.title }}</h4></a>
                <p>Status: {% if thread.is_locked %} Locked {% else %} Open {% endif %}</p>
            {% if not request.user.userprofile.role == 0 %}
                    <form action="{% url "boards:lock_thread" %}" method="post">
                    {% csrf_token %}
                        <input type="hidden" name="thread_id" value="{{ thread.id }}">
                        <input type="submit" value="{% if thread.is_locked %}Unlock{% else %}Lock Thread{% endif %}">
                    </form>
            {% endif %}

                <p>Last post on {{ thread.get_latest_post.created }} by <a
                        href="{% url "users:profile" thread.get_latest_post.posted_by.id %}">{{ thread.get_latest_post.posted_by.user }}</a>
                </p>
            </div>
        {% endfor %}
    {% endif %}


{% endblock %}

templates/board/index.html
{% extends 'base.html' %}
{% block content %}
    {% if request.user.is_anonymous %}
        <p>Please register <a href="{% url "users:register" %}">here</a></p>
    {% else %}
        <h1>Welcome {{ request.user.username }}</h1>

    {% endif %}

    <div>
        <h2><a href="{% url "boards:new_thread" %}">Create a thread</a></h2>
    </div>
    {% if request.user.userprofile.role == 2 %}
        <h2><a href="{% url "boards:new_board" %}">Create New Board</a></h2>
    {% endif %}

    <div>
        {% for board in boards %}
            <div class="board">
                <h3><a href="{% url "boards:board_page" board.id %}">{{ board.name }}</a></h3>
                {% if request.user.userprofile.role == 2 %}
                    <form method="post" action="{% url "boards:delete_board" %}">
                        {% csrf_token %}
                        <input type="hidden" name="board_id" value="{{ board.id }}">
                        <input type="submit" value="Delete Board">
                    </form>
                {% endif %}
                {% if board.threads.exists %}
                    <div class="thread">
                        <h4>
                            <a href="{% url "boards:thread_page" board.thread_with_latest_post.id %}">{{ board.thread_latest_post.title }}</a>
                        </h4>
                    </div>
                {% endif %}
                {% if board.thread_with_latest_post %}
                    <p>Thread with the most recent reply: {{ board.thread_with_latest_post }}</p>
                {% endif %}
                <p>Number of posts in this board: {{ board.total_posts }}</p>
                <p>Number of threads in this board:{{ board.threads.count }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/board/new_board.html
<form method="post" action="{% url "boards:new_board" %}">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Create Board">
</form>

templates/board/new_thread.html
{% extends "base.html" %}
{% block content %}
<form method="post" action="{% url "boards:new_thread" %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

templates/board/thread_page.html
{% extends "base.html" %}
{% block content %}
    <h1><a href="{% url "boards:board_page"  thread.board.id %}">{{ thread.board.name }}</a> > {{ thread.title }}</h1>
    <div class="thread-info">

    </div>
    {% for post in posts %}
        <div>
            {{ post.message }}
            <p>By: <a href="{% url "users:profile" post.posted_by.id %}">{{ post.posted_by }}</a> on {{ post.created }}
            </p>

        </div>
    {% endfor %}

    {% if not thread.is_locked %}
        <form method="post" action="{% url "boards:thread_page" thread.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
    {% else %}
        <div>
            <h4>Thread is now locked. You cannot post comments anymore.</h4>
        </div>
    {% endif %}
    <hr>

{% endblock %}