accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/<int:user_id>/', views.profile_page, name='profile'),
    path('ban/', views.ban_user, name='ban'),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.index, name='index'),
    path('thread', views.create_thread, name='new_thread'),
    path('thread/<int:thread_id>', views.thread_view, name='thread_page'),
    path('thread/lock/', views.lock_thread, name='lock_thread'),
    path('board/<int:board_id>', views.board, name='board_page'),
    path('board/new/', views.create_board, name='new_board'),
    path('board/delete/', views.delete_board, name='delete_board'),
]

bulletin_board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('accounts.urls')),
    path('', include('boards.urls')),
    path('api/', include('bulletin_board.api_router')),
    path('api-auth', include('rest_framework.urls')),
    path('users/', include('allauth.urls')),
]

templates/users/banned.html
{% extends 'base.html' %}
{% block content %}
    <h1>Sorry you're banned</h1>
{% endblock %}

templates/users/login.html
<div>
<form action="{% url "users:login" %}" method="post">
    <h3>Login</h3>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
</div>

<div>
    <h3>No existing account?</h3>
    <p><a href="{% url "users:register" %}">Sign Up</a></p>
       <p><a href="{% url "google_login" %}">Sign Up With Google</a></p>
</div>

templates/users/profile.html
{% extends "base.html" %}
{% block content %}
    <p>Username:{{ user }}</p>
    <p>Account Status:{% if not user.is_banned %}Active{% else %}Banned{% endif %}</p>
    {% if not request.user.userprofile.role == 0 and user.role == 0 %}
        <form method="post" action="{% url "users:ban" %}">
            {% csrf_token %}
            <input type="hidden" name="user_id" value="{{ user.id }}">
            <input type="Submit"
                   value="{% if not user.is_banned %}
                        Ban Account
                        {% else %}
                        Unban Account
                        {% endif %}">
        </form>
    {% endif %}
    <div>
        <h4>Posts</h4>
        <ul>
            {% for post in user.recent_posts %}
                <li>
                    <div>
                        {{ post.message }}
                        <p>Posted on {{ post.thread }} at {{ post.created }}</p>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/users/register.html
<form method="post" action="{% url "users:register" %}">
    {% csrf_token %}
    {{ registration_form.as_p }}
    <input type="submit" value="Submit">
</form>